<a href="https://colab.research.google.com/github/samratapoorv/Anime-Recommendation_system/blob/main/AnimeRecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [ ]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/content/myanime.csv')

In [ ]:
# printing the first 5 rows of the dataframe
movies_data.head()

Anime  \
0   Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season   
1                               Kanojo, Okarishimasu   
2                             The God of High School   
3  Maou Gakuin no Futekigousha: Shijou Saikyou no...   
4                     Enen no Shouboutai: Ni no Shou   

                                             Genre  \
0                 ['Drama', 'Fantasy', 'Suspense']   
1                            ['Comedy', 'Romance']   
2  ['Action', 'Fantasy', 'Sci-Fi', 'Supernatural']   
3                            ['Action', 'Fantasy']   
4                       ['Action', 'Supernatural']   

                                         Description             Studio  \
0  A reunion that was supposed to spell the arriv...          White Fox   
1  Kazuya Kinoshita is a 20-year-old college stud...  TMS Entertainment   
2  The "God of High School" tournament has begun,...              MAPPA   
3  In the distant past, a war between humans and ...       SILVER LINK.   
4  After his confrontation in the Nether with his...   David Production   

           Year  Rating  Index  
0   Jul 8, 2020    8.37      1  
1  Jul 11, 2020     NaN      2  
2   Jul 6, 2020     NaN      3  
3   Jul 4, 2020     NaN      4  
4   Jul 4, 2020     NaN      5

In [ ]:
# number of rows and columns in the data frame
movies_data.shape

(2981, 7)

In [ ]:
# selecting the relevant features for recommendation

selected_features = ['Genre','Description']
print(selected_features)

['Genre', 'Description']


In [ ]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
# combining all the 5 selected features

combined_features = movies_data['Genre']+' '+movies_data['Description']

In [ ]:
print(combined_features)

0       ['Drama', 'Fantasy', 'Suspense'] A reunion tha...
1       ['Comedy', 'Romance'] Kazuya Kinoshita is a 20...
2       ['Action', 'Fantasy', 'Sci-Fi', 'Supernatural'...
3       ['Action', 'Fantasy'] In the distant past, a w...
4       ['Action', 'Supernatural'] After his confronta...
                              ...                        
2976    Sci-Fi The distant future. After reaching its ...
2977    Slice of Life Anime adaptation of the spin-off...
2978    Comedy Fourth season of Yatogame-chan Kansatsu...
2979    Comedy Based on characters from the free to pl...
2980    Comedy Ken Tamaki defeats corrupt organization...
Length: 2981, dtype: object


In [ ]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 17483)	0.026582619752869394
  (0, 12502)	0.02599496093279664
  (0, 23221)	0.02651737997231845
  (0, 11792)	0.06646628993913645
  (0, 14765)	0.07685197702934002
  (0, 12243)	0.08547287622576134
  (0, 18218)	0.059191742200972675
  (0, 17307)	0.08440217946680006
  (0, 12189)	0.05615884521608353
  (0, 9388)	0.05746970292181236
  (0, 9282)	0.11408427579194366
  (0, 2760)	0.09531365311051412
  (0, 16465)	0.09762335120974718
  (0, 18466)	0.11839472539015433
  (0, 10317)	0.1056993402007177
  (0, 8529)	0.11839472539015433
  (0, 10871)	0.11074083133289814
  (0, 23689)	0.08440217946680006
  (0, 16746)	0.07565266678316916
  (0, 18392)	0.056637078766468
  (0, 18403)	0.056637078766468
  (0, 2468)	0.07685197702934002
  (0, 17614)	0.09642404096357632
  (0, 20153)	0.11839472539015433
  (0, 3587)	0.08923841561852121
  :	:
  (2980, 4873)	0.1618586400578336
  (2980, 19614)	0.05419107878252507
  (2980, 17532)	0.11978163400355453
  (2980, 19824)	0.1636333637050092
  (2980, 6526)	0.08242492606782477
  

Cosine Similarity

In [ ]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.0526598  0.08248944 ... 0.02293914 0.04411839 0.04313867]
 [0.0526598  1.         0.05180014 ... 0.00208161 0.03466195 0.06469494]
 [0.08248944 0.05180014 1.         ... 0.00591111 0.03002894 0.04564306]
 ...
 [0.02293914 0.00208161 0.00591111 ... 1.         0.01349799 0.00498417]
 [0.04411839 0.03466195 0.03002894 ... 0.01349799 1.         0.03259814]
 [0.04313867 0.06469494 0.04564306 ... 0.00498417 0.03259814 1.        ]]


In [ ]:
print(similarity.shape)

(2981, 2981)


Getting the movie name from the user

In [ ]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : one piece


In [ ]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['Anime'].tolist()
print(list_of_all_titles)

['Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season', 'Kanojo, Okarishimasu', 'The God of High School', 'Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou', 'Enen no Shouboutai: Ni no Shou', 'Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan', 'Great Pretender', 'Sword Art Online: Alicization - War of Underworld 2nd Season', 'Uzaki-chan wa Asobitai!', 'Deca-Dence', 'Monster Musume no Oishasan', 'Peter Grill to Kenja no Jikan', 'Dokyuu Hentai HxEros', 'No Guns Life 2nd Season', 'Gibiate', 'Koi to Producer: EVOL×LOVE', 'Lapis Re:LiGHTs', 'Muhyo to Rouji no Mahouritsu Soudan Jimusho 2nd Season', 'Ninja Collection', 'Umayon', 'Chou Futsuu Toshi Kashiwa Densetsu R', 'Arad: Gyakuten no Wa', 'Get Up! Get Live! #Geragera', 'Hulaing Babies Aratame: Staying Babies', 'Taeko no Nichijou 2nd Season', 'One Piece', 'Black Clover', 'Boruto: Naruto Next Generations', 'Shokugeki no Souma: Gou no Sara', 'Fruits Basket 2nd Season', 'Fugou Keiji:

In [ ]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['One Piece', 'Ange Vierge']


In [ ]:
close_match = find_close_match[0]
print(close_match)

One Piece


In [ ]:
# finding the index of the movie with title
index_of_the_movie = movies_data[movies_data.Anime == close_match]['Index'].values[0]
print(index_of_the_movie)

26


In [ ]:
# getting a list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.0998040791309606), (1, 0.06120153771586368), (2, 0.07038396473350861), (3, 0.12102408905122125), (4, 0.08712881110003298), (5, 0.0932979081432432), (6, 0.0882590446260005), (7, 0.09935426440939218), (8, 0.09000426817036213), (9, 0.11092280395500641), (10, 0.0503588238076448), (11, 0.07532658178095229), (12, 0.08303114653330201), (13, 0.008315541646307496), (14, 0.06913353001314368), (15, 0.1105118615870175), (16, 0.07118818521009943), (17, 0.012736457239045759), (18, 0.03697354136476806), (19, 0.02447369957946794), (20, 0.007287372116755876), (21, 0.016585610285385296), (22, 0.07061359261833693), (23, 0.027415793940799727), (24, 0.007373331299913229), (25, 0.1071095605732392), (26, 1.0), (27, 0.0684883074237482), (28, 0.08338760811523832), (29, 0.09214937432797211), (30, 0.05686554533805158), (31, 0.06857189845035186), (32, 0.07961735475923734), (33, 0.07381981107644257), (34, 0.09352803346072011), (35, 0.07376546988983416), (36, 0.06801596988232562), (37, 0.05414144033775245), 

In [ ]:
len(similarity_score)

2981

In [ ]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(26, 1.0), (1627, 0.24349465959737457), (2062, 0.16765227590692813), (78, 0.1545309968540938), (2289, 0.15209586799039337), (462, 0.14355588436198502), (2127, 0.14320533240900013), (1391, 0.1423452473877554), (2533, 0.14182489815864344), (491, 0.1402176980371881), (886, 0.1393244136703151), (1182, 0.13895441816418005), (964, 0.13680631827291032), (2734, 0.13583074203325404), (696, 0.134912139377066), (1769, 0.1337624759964533), (454, 0.1313544594676171), (1464, 0.12887307252924615), (2649, 0.12784749457027017), (2777, 0.1262974131791177), (317, 0.12629136012924266), (1812, 0.12625615011957314), (1731, 0.126196847834032), (2764, 0.12584031219184486), (929, 0.12502654625379786), (1163, 0.12340136676870185), (231, 0.12292260862003668), (2641, 0.12215641673105128), (2307, 0.12192496453329149), (3, 0.12102408905122125), (428, 0.12085240953967881), (93, 0.12048695035929703), (1382, 0.12043397602513294), (1625, 0.12035624505908621), (679, 0.1203073489882345), (2207, 0.11999054654114047), (17

In [ ]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['Anime'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Black Clover
2 . Hidamari Sketch
3 . Hidamari Sketch x ☆☆☆
4 . Shironeko Project: Zero Chronicle
5 . Mirai Nikki (TV)
6 . Caligula (TV)
7 . Ichiban Ushiro no Daimaou
8 . Mahou Sensei Negima!
9 . Mahou Sensou
10 . Ao no Exorcist: Kyoto Fujouou-hen
11 . Garo: Honoo no Kokuin
12 . G-On Riders
13 . Arslan Senki (TV)
14 . King's Raid: Ishi wo Tsugumono-tachi
15 . Kono Danshi, Mahou ga Oshigoto Desu.
16 . Ayakashi
17 . Mahou Shoujo Site
18 . Ueki no Housoku
19 . Love Live! School Idol Project 2nd Season
20 . Boku no Hero Academia 5th Season
21 . Ryuuou no Oshigoto!
22 . Hidamari Sketch x 365
23 . Kiss Dum: Engage Planet
24 . Scarlet Nexus
25 . Joukamachi no Dandelion
26 . Final Fantasy: Unlimited
27 . Kanata no Astra
28 . Hitsugi no Chaika
29 . Hagure Yuusha no Aesthetica
